services: docker

jobs:
  include:
  - stage: build
    env: STABLE
    install:
      - docker build -t openquake/mapproxy . 
  - stage: build
    env: MASTER
    install:
      - docker build -t openquake/mapproxy . 

script:
    - docker run --rm -ti -u 500:500 openquake/mapproxy mapproxy-util --version | grep -w "MapProxy"
