---
name: docker buil and push on dockerhub
on:
  workflow_dispatch:
    inputs:
      version:
        description: Image Tag 
        default: nightly
        required: true
      git-ref:
        description: Git Ref (Optional)    
        default: master
        required: false  

jobs:
  docker:
    name: Build image and push after successfull calculation
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Build image engine with tag nightly
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_TAG: ${{ github.event.inputs.version }}
          REPO_REF: ${{ github.event.inputs.git-ref }}
        id: docker_mapproxy
        run: docker build --build-arg oq_branch=$REPO_REF -t openquake/engine:$DOCKER_TAG -f docker/Dockerfile.dev docker
      - name: List Image
        run: |
          docker image ls
      - name: Run calcs on single docker
        run: |
          time docker run openquake/engine:$DOCKER_TAG "oq engine --run /usr/src/oq-engine/demos/risk/ScenarioDamage/job_hazard.ini /usr/src/oq-engine/demos/risk/ScenarioDamage/job_risk.ini"
      - name: push image engine with tag nightly on docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_TAG: ${{ github.event.inputs.version }}
        run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          docker push openquake/mapproxy-serveropenquake/:$DOCKER_TAG
