---
name: docker build and push on dockerhub
on:
  workflow_dispatch:
    inputs:
      version:
        description: Image Tag 
        default: latest
        required: true
      git-ref:
        description: Git Ref
        default: master
        required: true  

jobs:
  docker:
    name: Build image and push on dockerhub
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Clone Repository (Master)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Build image engine with tag ${{ github.event.inputs.version }}
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_TAG: ${{ github.event.inputs.version }}
          REPO_REF: ${{ github.event.inputs.git-ref }}
        id: docker_mapproxy
        run: docker build --build-arg oq_branch=$REPO_REF -t openquake/mapproxy-server:$DOCKER_TAG -f Dockerfile
      - name: List Image
        run: |
          docker image ls
      - name: push mapproxy image with tag ${{ github.event.inputs.version }} on dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_TAG: ${{ github.event.inputs.version }}
        run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          docker push openquake/mapproxy-server:$DOCKER_TAG
