---
name: docker build and push on dockerhub
on:
  workflow_dispatch:
    inputs:
      tags:
        description: Comma-separated list of tags
        default: unstable
        required: false
      pkg:
        description: Pkg of mapproxy
        default: https://github.com/mapproxy/mapproxy/archive/refs/tags/1.13.0.zip
        required: true  

jobs:
  docker:
    name: Build image and push on dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Check tag extraction
        shell: bash
        run: set -x ; for tag in $(echo ${{ github.event.inputs.tags }} | tr , '\n'); do echo "-t openquake/mapproxy-server:$tag " | tr -d '\n'; done
      - name: Extract tag names
        shell: bash
        run: echo "##[set-output name=tags;]" | tr -d '\n'; for tag in $(echo ${{ github.event.inputs.tags }} | tr , '\n'); do echo "-t openquake/mapproxy-server:$tag " | tr -d '\n'; done
        id: extract_tag_names
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Clone Repository (Master)
        uses: actions/checkout@v2
        if: ${{ steps.extract_branch.outputs.branch }} != ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: ${{ steps.extract_branch.outputs.branch }} != ''
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Build image with tags ${{ steps.extract_tags.outputs.tags }}
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          REPO_REF: ${{ steps.extract_branch.outputs.branch }}
        id: docker_mapproxy
        run: set -x ; eval docker build ${{ steps.extract_tags.outputs.tags}} -f Dockerfile .
      - name: List Image
        run: |
          docker image ls
      - name: push mapproxy image with tags ${{ steps.extract_tags.outputs.tags }} on dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          docker push openquake/mapproxy-server
