---
name: docker build and push on dockerhub
on:
  workflow_dispatch:
    inputs:
      version:
        description: Image Tag 
        default: unstable
        required: true
      version2:
        description: Extra Image Tag 
        default: 
        required: false
      pkg:
        description: Pkg of mapproxy
        default: https://github.com/mapproxy/mapproxy/archive/refs/tags/1.13.0.zip
        required: true  

jobs:
  docker:
    name: Build image and push on dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Clone Repository (Master)
        shell: bash
        uses: actions/checkout@v2
        if: ${{ steps.extract_branch.outputs.branch }} != ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: ${{ steps.extract_branch.outputs.branch }} != ''
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Build image engine with tag ${{ github.event.inputs.version }}
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_TAG: ${{ github.event.inputs.version }}
          REPO_REF: ${{ steps.extract_branch.outputs.branch }}
        id: docker_mapproxy
        run: docker build --build-arg oq_branch=$REPO_REF -t openquake/mapproxy-server:$DOCKER_TAG -f Dockerfile
      - name: List Image
        run: |
          docker image ls
      - name: push mapproxy image with tag ${{ github.event.inputs.version }} on dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_TAG: ${{ github.event.inputs.version }}
        run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          docker push openquake/mapproxy-server:$DOCKER_TAG
